### PR TITLE
Make sure to export GO111MODULE=on on installation

### PR DESCRIPTION
**Pull request by hairyhenderson**
Fixes issues like seen in https://github.com/motemen/gore/issues/196

### CODE REVIEW

**Comment by itchyny** [comment]
I'd rather prefer using `env` command not to pollute the environment.

**Comment by hairyhenderson** [comment]
@itchyny feel free to make modifications then!

**Comment by itchyny** [comment]
Basically this NOT necessary so closing. Go automatically enables go modules unless globally disabled.

**Comment by hairyhenderson** [comment]
@itchyny the issue #196 and my own experience contradicts that statement... But it's your call. I've already decided gore won't fit my use-cases.

**Pull request closed without merging**
