### PR TITLE
Import packages from external golang source code

### PR DESCRIPTION
**Pull request by tcnksm**
I want to import package from external golang source. 
This pull request enables that by `-include` option. 

```bash
$ cd $GOPATH/src/github.com/motemen/gore
$ gore -include main.go
gore version 0.0.0  :help for help
gore> homedir.Dir()
"/Users/tcnksm"
nil
gore>
```

I'm not sure implicit vs. explicit import  (cf. https://github.com/motemen/gore/pull/2)
But for me, session should be what I expected like ruby's `irb`. 

This is just proposal.

### CODE REVIEW

**Comment by mattn** [comment]
I want to use with multiple files or directory

**Comment by motemen** [comment]
So this PR enables importing packages which are imported by a file specified. Seems good, but I think capability of using functions or variables defined in external files, not only importing packages, would be better (though I don't know we can achieve it). How about that? And would you show me what behavior of irb you want in gore, as I am not familiar with it?

**Comment by tcnksm** [comment]
> multiple files or directory

and 

> capability of using functions or variables defined in external files, not only importing packages, would be better 

are great I think (I'm also not sure I can implement importing function). 

And about `irb`, what I want to say is explicit import (in ruby it is `require`) would be better.

**Comment by tcnksm** [comment]
I've finished. 

This PR enables us to include external golang sources and, 

- Include packages from external golang sources
- Enable to execute function defined in external golang sources

Here is example usages, https://gist.github.com/tcnksm/46a7eefcfe63f2930082

**Comment by motemen** [comment]
Thank you for the pull request and sorry for such a late reply.

Mostly looks good, but one point: we need a good reason to import packages imported by the included files in the repl session, as including files does not mean importing packages used by them. (I guess it helpful for repl users, so let's keep the behavior as is.)

Then, how about changing the `-include=file,...` flag to `-context=file,...`, which I think fit better to what it does? Can I apply that change (and some small fixes) and merge this PR?

**Comment by tcnksm** [comment]
>  we need a good reason to import packages imported by the included files in the repl session

For me, include package one by one is tired, I want to try packages in some go source file which currently I'm developing. 

> how about changing the -include=file,... flag to -context=file,...

`-include=file` is more intuitive UI for me. But this is just my opinion so `-context` is ok I think.

**Comment by motemen** [comment]
Finally merged it :smile:  Thanks a lot!

**Comment by tcnksm** [comment]
Thanks :ok_woman:

**Pull request merged**
