### PR TITLE
Recursively import packages if desired

### PR DESCRIPTION
**Pull request by zaquestion**
Added a flag "-recursive" that will recursive import packages passed with the pkg flag.

This probably shouldn't be merged in this state, I wanted it in the moment so hacked it together. Putting up this PR to see if there is interest from @motemen and what you would want the feature to look like. Happy to rework the change if its something you would like to add. I found it very useful since the project I'm working on has 145 packages under it.

### CODE REVIEW

**Comment by zaqthefreshman** [comment]
Failing build is not due to this PR same error seems to be happening on some other PRs

**Comment by motemen** [comment]
Thank you.

By `includePackage` gore includes files to the session's main package, so recursive including may cause unwanted behaviors e.g. name collision, and may not be very useful.

I think it would be nicer to add import declarations recursively rather than including files.
For example if we invoke gore like

```
gore -pkg=path/to/pkg/...
```

Creating a repl session like:

```go
import . "path/to/pkg"
import "path/to/pkg/a"
import "path/to/pkg/b"
...

func main() {
  // session code goes here
}
```

How about that?

**Comment by zaqthefreshman** [comment]
Ah I did not realize that when I hacked it together. I like your solution much better, thanks for taking a look and thinking about it. I'll get that implemented sometime this weekend (most likely)

**Comment by zaquestion** [comment]
Closing as I (obviously) have not found time to integrate feedback. Soon still I hope

**Pull request closed without merging**
